@startuml

title __MODEL's Class Diagram__\n

  namespace com.reservation_system {
    namespace model {
      class com.reservation_system.model.ErrorResponse {
          - exception : String
          - fieldErrors : List<FieldError>
          - httpStatus : Integer
          - message : String
          + getException()
          + getFieldErrors()
          + getHttpStatus()
          + getMessage()
          + setException()
          + setFieldErrors()
          + setHttpStatus()
          + setMessage()
      }
    }
  }
  

  namespace com.reservation_system {
    namespace model {
      class com.reservation_system.model.FieldError {
          - errorCode : String
          - field : String
          + getErrorCode()
          + getField()
          + setErrorCode()
          + setField()
      }
    }
  }
  

  namespace com.reservation_system {
    namespace model {
      class com.reservation_system.model.ReservationDTO {
          - endTime : LocalTime
          - id : Long
          - reservationDate : LocalDate
          - startTime : LocalTime
          - user : Long
          + getEndTime()
          + getId()
          + getReservationDate()
          + getStartTime()
          + getUser()
          + setEndTime()
          + setId()
          + setReservationDate()
          + setStartTime()
          + setUser()
      }
    }
  }
  

  namespace com.reservation_system {
    namespace model {
      class com.reservation_system.model.UserDTO {
          - id : Long
          + getId()
          + setId()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
