@startuml

title __MODEL's Class Diagram__\n

  namespace com.reservation_system {
    namespace model {
      enum AmenityType {
        GYM
        POOL
        SAUNA
        name
      }
    }
  }
  

  namespace com.reservation_system {
    namespace model {
      class com.reservation_system.model.Reservation {
          - dateCreated : OffsetDateTime
          - endTime : LocalTime
          - id : Long
          - lastUpdated : OffsetDateTime
          - reservationDate : LocalDate
          - startTime : LocalTime
          + Reservation()
          + Reservation()
          {static} + builder()
          + getAmenityType()
          + getDateCreated()
          + getEndTime()
          + getId()
          + getLastUpdated()
          + getReservationDate()
          + getStartTime()
          + getUser()
          + prePersist()
          + preUpdate()
          + setAmenityType()
          + setDateCreated()
          + setEndTime()
          + setId()
          + setLastUpdated()
          + setReservationDate()
          + setStartTime()
          + setUser()
      }
    }
  }
  

  namespace com.reservation_system {
    namespace model {
      class com.reservation_system.model.Reservation.ReservationBuilder {
          - dateCreated : OffsetDateTime
          - endTime : LocalTime
          - id : Long
          - lastUpdated : OffsetDateTime
          - reservationDate : LocalDate
          - startTime : LocalTime
          + amenityType()
          + build()
          + dateCreated()
          + endTime()
          + id()
          + lastUpdated()
          + reservationDate()
          + startTime()
          + toString()
          + user()
          ~ ReservationBuilder()
      }
    }
  }
  

  namespace com.reservation_system {
    namespace model {
      class com.reservation_system.model.User {
          - dateCreated : OffsetDateTime
          - fullName : String
          - id : Long
          - lastUpdated : OffsetDateTime
          - passwordHash : String
          - reservations : Set<Reservation>
          - username : String
          + User()
          + User()
          + User()
          {static} + builder()
          + getDateCreated()
          + getFullName()
          + getId()
          + getLastUpdated()
          + getPasswordHash()
          + getReservations()
          + getUsername()
          + prePersist()
          + preUpdate()
          + setDateCreated()
          + setFullName()
          + setId()
          + setLastUpdated()
          + setPasswordHash()
          + setReservations()
          + setUsername()
      }
    }
  }
  

  namespace com.reservation_system {
    namespace model {
      class com.reservation_system.model.User.UserBuilder {
          - dateCreated : OffsetDateTime
          - fullName : String
          - id : Long
          - lastUpdated : OffsetDateTime
          - passwordHash : String
          - reservations : Set<Reservation>
          - username : String
          + build()
          + dateCreated()
          + fullName()
          + id()
          + lastUpdated()
          + passwordHash()
          + reservations()
          + toString()
          + username()
          ~ UserBuilder()
      }
    }
  }
  

  com.reservation_system.model.Reservation o-- com.reservation_system.model.AmenityType : amenityType
  com.reservation_system.model.Reservation o-- com.reservation_system.model.User : user
  com.reservation_system.model.Reservation +-down- com.reservation_system.model.Reservation.ReservationBuilder
  com.reservation_system.model.Reservation.ReservationBuilder o-- com.reservation_system.model.AmenityType : amenityType
  com.reservation_system.model.Reservation.ReservationBuilder o-- com.reservation_system.model.User : user
  com.reservation_system.model.User +-down- com.reservation_system.model.User.UserBuilder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
