@startuml

title __RESERVATION-SYSTEM's Class Diagram__\n

  namespace com.reservation_system {
    class com.reservation_system.HomeController {
    }
  }
  

  namespace com.reservation_system {
    class com.reservation_system.ReservationSystemApplication {
    }
  }
  

  namespace com.reservation_system {
    namespace config {
      class com.reservation_system.config.DomainConfig {
      }
    }
  }
  

  namespace com.reservation_system {
    namespace config {
      class com.reservation_system.config.JacksonConfig {
      }
    }
  }
  

  namespace com.reservation_system {
    namespace config {
      class com.reservation_system.config.RestExceptionHandler {
      }
    }
  }
  

  namespace com.reservation_system {
    namespace domain {
      class com.reservation_system.domain.Reservation {
      }
    }
  }
  

  namespace com.reservation_system {
    namespace domain {
      class com.reservation_system.domain.User {
      }
    }
  }
  

  namespace com.reservation_system {
    namespace model {
      class com.reservation_system.model.ErrorResponse {
      }
    }
  }
  

  namespace com.reservation_system {
    namespace model {
      class com.reservation_system.model.FieldError {
      }
    }
  }
  

  namespace com.reservation_system {
    namespace model {
      class com.reservation_system.model.ReservationDTO {
      }
    }
  }
  

  namespace com.reservation_system {
    namespace model {
      class com.reservation_system.model.UserDTO {
      }
    }
  }
  

  namespace com.reservation_system {
    namespace repos {
      interface com.reservation_system.repos.ReservationRepository {
      }
    }
  }
  

  namespace com.reservation_system {
    namespace repos {
      interface com.reservation_system.repos.UserRepository {
      }
    }
  }
  

  namespace com.reservation_system {
    namespace rest {
      class com.reservation_system.rest.ReservationResource {
      }
    }
  }
  

  namespace com.reservation_system {
    namespace rest {
      class com.reservation_system.rest.UserResource {
      }
    }
  }
  

  namespace com.reservation_system {
    namespace service {
      class com.reservation_system.service.ReservationService {
      }
    }
  }
  

  namespace com.reservation_system {
    namespace service {
      class com.reservation_system.service.UserService {
      }
    }
  }
  

  com.reservation_system.domain.Reservation o-- com.reservation_system.domain.User : user
  com.reservation_system.rest.ReservationResource o-- com.reservation_system.service.ReservationService : reservationService
  com.reservation_system.rest.UserResource o-- com.reservation_system.service.UserService : userService
  com.reservation_system.service.ReservationService o-- com.reservation_system.repos.ReservationRepository : reservationRepository
  com.reservation_system.service.ReservationService o-- com.reservation_system.repos.UserRepository : userRepository
  com.reservation_system.service.UserService o-- com.reservation_system.repos.UserRepository : userRepository


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
